# @package _group_
env: "fetch_custom"
# term_fn is set automatically by mbrl.util.env.EnvHandler.make_env

num_steps: 30000
epoch_length: 10
num_elites: 2
patience: 10
model_lr: 0.0003
model_wd: 5e-5
model_batch_size: 32
validation_ratio: 0.2
freq_train_model: 2
effective_model_rollouts_per_step: 4
rollout_schedule: [20, 100, 1, 25]
num_sac_updates_per_step: 2
sac_updates_every_steps: 1
num_epochs_to_retain_sac_buffer: 1

sac_gamma: 0.99
sac_tau: 0.005
sac_alpha: 0.2
sac_policy: "Gaussian"
sac_target_update_interval: 4
sac_automatic_entropy_tuning: false
sac_target_entropy: -1 # ignored, since entropy tuning is false
sac_hidden_size: 1024
sac_lr: 0.0001
sac_batch_size: 32

# custom
algorithm:
  learned_rewards: false
  initial_exploration_steps: 100
  random_initial_explore: false

dynamics_model:
  ensemble_size: 1

agent:
  _target_: mbrl.third_party.pytorch_sac_pranz24.td3.TD3 # mbrl.third_party.pytorch_sac_pranz24.sac.SAC , mbrl.third_party.pytorch_sac_pranz24.td3.TD3

do_imag_training: true

real_data_ratio: 0.0